#!/bin/sh
set -eu

TARGET=
for OPTION in $(cat /proc/cmdline); do
  case "$OPTION" in
    taichios.install=*) TARGET=${OPTION#taichios.install=} ;;
  esac
done

test -n "$TARGET" || exit 0
set +e
/usr/local/sbin/taichios-install --disk "$TARGET" --yes
STATUS=$?
set -e
if test "$STATUS" -ne 0; then
  echo "TAICHIOS_INSTALL_FAILED status=$STATUS" > /dev/ttyS0
  exit "$STATUS"
fi
echo TAICHIOS_INSTALL_COMPLETE > /dev/ttyS0
systemctl poweroff
